Generating pipelines...
1 pipelines have been generated.

Pipeline1: Plotting a heatmap of the samples.
[ 2:09PM] 1.convert_signal_to_tdf
[ 2:10PM] 2.log_signal
[ 2:10PM] 3.fill_missing_with_zeros
[ 2:10PM] 4.convert_signal_to_pcl
[ 2:10PM] 5.center_genes
[ 2:10PM] 6.plot_signal_heatmap
Traceback (most recent call last):
  File "/home/xchen/chencode/Betsy/scripts/run_protocol.py", line 203, in <module>
    main()
  File "/home/xchen/chencode/Betsy/scripts/run_protocol.py", line 192, in main
    parameters,clean_up=args.clean_up)
  File "/home/xchen/chencode/Betsy/scripts/run_protocol.py", line 69, in run_protocol
    out_files = rule_engine.run_pipeline(pipeline, objects,clean_up=clean_up)
  File "/home/xchen/chencode/Betsy/Betsy/rule_engine.py", line 224, in run_pipeline
    analysis,objects,pipeline_sequence,clean_up=clean_up)
  File "/home/xchen/chencode/Betsy/Betsy/rule_engine.py", line 169, in run_module
    analysis.parameters, objects, pipeline_sequence)
  File "/home/xchen/chencode/Betsy/Betsy/modules/plot_signal_heatmap.py", line 29, in run
    raise ValueError(error_message)
ValueError: Traceback (most recent call last):
  File "/home/xchen/chencode/scripts/arrayplot.py", line 2279, in <module>
    main()
  File "/home/xchen/chencode/scripts/arrayplot.py", line 2271, in main
    options.width, options.height)
AssertionError: 3804x546754 plot too big [200:10].

